### ISSUE TITLE
AR & LL - poem text not appearing in the grid

### ISSUE THREAD

**Issue by joz-f** [theodi/firetruck#44]

**Comment by stephendwolff** [comment]
@joz-f this is a bit odd. i have the same code running locally and on the staging server, so something isn't quite right about the ODI deploy

**Comment by stephendwolff** [comment]
It seems to take a few seconds to load the font file(s) (xhr - see inspector). So, that is stopping the rendering of the font offscreen to be used to show the poem. Netflify configuration?

**Comment by stephendwolff** [comment]
<img width="1306" alt="Screenshot 2020-11-06 at 09 14 15" src="https://user-images.githubusercontent.com/25349/98348375-9073b600-2010-11eb-89f9-ad756c6e1e53.png">

**Comment by stephendwolff** [comment]
@rachelwilson could you look in Netlify (if that's what you're using still), and check whether there are any settings to let the font file download quicker? it's taking significantly longer than on our staging server.

**Comment by rachelwilson** [comment]
I can take a look but i have to warn you i'm no expert in Netlify, or performance optimisation.  Let's see what google throws up though

Just out of interest, is it any quicker on subsequent page loads?

**Comment by stephendwolff** [comment]
It's quicker on subsequent page loads if i enable the cache yes. It's just odd that it's slower on the 'production' server compared to the 'staging' server. I'll see if there is a smaller font file available too.

**Comment by rachelwilson** [comment]
Still in information gathering mode so bear with me while i ask some basic questions and expose the holes in my understanding...

Q. How is firetruck deployed on the staging server?

My mental model of how the internet works might be wrong but, how i think it works is: 
1. The font files reside on the web server, or in Netlify's case probably a CDN. 
2. The first time the page is loaded the fonts should be downloaded and cached in the browser
3. So with a clean browser cache, both staging and netlify should give similar page load times

Can you verify point 3 for me? 

Because if, on subsequent loads both Netlify and staging give wildly different load times, there must be a problem with cache TTLs and Netlify is going to the source every time.

But, based on that (possibly wonky) logic my theory would be that your browser had already cached the fonts from the staging server long ago and so werent noticing the load time anymore.

FWIW there are [some suggestions out there](https://www.reddit.com/r/webdev/comments/hw4to2/my_static_website_built_with_gatsbyreact_hosted/) about pre-loading fonts and using a system font default while the page is loading to reduce the apparent load time.

**Comment by rachelwilson** [comment]
I'm puzzled why the font file in question is so large.  23MB?   Is that right?

Is it _just_ Arial? Because that should be available as a system font

**Comment by rachelwilson** [comment]
~The other thing i dont quite understand is that i thought font files should be cached across sites? I didnt think they were site specific like cookies are~  I was wrong about that. Apparently [they're site specific](https://stackoverflow.com/questions/19453147/do-custom-font-face-cache-between-domains). Perhaps there's something here about Netlify using of CDNs, i think i read something about rewriting URLs for the locations of CSS "stuff" like the fonts, to point to the CDN locations. Which would explain why your first Netlify page load couldnt use your browser cache

Something to investigate would be if you notice the same slowness after each netlify deploy - or whether the netlify reuses the CDN urls which persists after subsequent deploys (you'd hope so!)

**Comment by joz-f** [comment]
Wow Arial.ttf is massive, and there are unnecessary 'specimen' files in the other two which I could go through and remove.

Roboto and PT Mono are the special fonts. 

@stephendwolff can we remove Arial - I just checked and it is a system font on Windows and Macs. Maybe this is a hang over from the RaspberryPi and Ubuntu version?

**Comment by stephendwolff** [comment]
@rachelwilson and @joz-f, the font files are being loaded by 'P5js' (the animation framework) to render the text of the poems to an offscreen browser in order to animate the 'split flap' effect. The arial font is used for Greek and Maltese, as PT Mono doesn't have glyphs for characters needed, and thus look a bit 'odd'.

If Arial was just being used by HTML/CSS, then yes it could be removed, but we do need a font (probably a Unicode one) for Greek and Maltese. It might even be the mac system font version which is being uploaded. 

I always have my cache disabled when developing - so the difference between the servers is definitely due to the servers themselves rather than an issue local to my browser. 23Mb isn't that big on a fast broadband connection these days, but yes, hopefully we can find something smaller or use Netlify CDN. The site won't be using a CDN unless the whole site is via Netlify. Static assets are all referenced locally (although i did spy one which a full URL which was a bit odd).

**Comment by rachelwilson** [comment]
Hi Stephen, 

Hmm, interesting.  I'll ponder your reply and rummage more in the bowels of netlify.

in the meantime could you answer the following - to help me comprehend how it all works and where the differences might be. Specifically:
* How is firetruck deployed to the staging server?  (and what/where is that staging server?)
* ~Can you verify point 3 for me?~  I've verified this myself. I can confirm there's is a significant difference
* I wasnt sure what you meant by "The site won't be using a CDN unless the whole site is via Netlify."  In what way _isnt_ the whole site via netlify at the moment?

Are you able to follow instructions to (a) preload (b) use default system fonts while the custom fonts are loading. That's probably an optimisation worth doing anyway.

**Comment by rachelwilson** [comment]
FYI I've raised a [support query with Netlify](https://community.netlify.com/t/slow-download-speed-for-static-asset-fonts/25863/7)

The strong message coming back is to reduce the size of the font file.  "more likely in the <50kb realm. It might be worth investigating if this is really as intended."

**Comment by stephendwolff** [comment]
I've changed the font used, so now it's no longer slow to load. Fixed!

**Comment by rachelwilson** [comment]
Great, thank you!
